version: "3"
services:
  app:
    container_name: nginxProxy
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80"
      - "443:443"
      - "81:81" # Admin Web Port
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - server-dev

networks:
  server-dev:
    driver: bridge
    external: true
